In [44]:
import pandas as pd

In [45]:
df=pd.read_csv('employees.csv')

In [46]:
df

   eid   ename    city
0    1    amit     kop
1    2   kumar   kagal
2    3   vijay    pune
3    4  ramesh     mum
4    5    ravi  satara

In [47]:
df1=pd.read_csv('salary.csv')

In [48]:
df1

   eid   dept
0    1     it
1    2   mech
2    3  civil
3    6  elect
4    7     ai

In [49]:
df.merge(df1,on='eid',how='inner')

   eid  ename   city   dept
0    1   amit    kop     it
1    2  kumar  kagal   mech
2    3  vijay   pune  civil

In [50]:
df.merge(df1,on='eid',how='left')

   eid   ename    city   dept
0    1    amit     kop     it
1    2   kumar   kagal   mech
2    3   vijay    pune  civil
3    4  ramesh     mum    NaN
4    5    ravi  satara    NaN

In [51]:
df.merge(df1,on='eid',how='right')

   eid  ename   city   dept
0    1   amit    kop     it
1    2  kumar  kagal   mech
2    3  vijay   pune  civil
3    6    NaN    NaN  elect
4    7    NaN    NaN     ai

In [52]:
joins=df.merge(df1,on='eid',how='outer')

In [53]:
joins

   eid   ename    city   dept
0    1    amit     kop     it
1    2   kumar   kagal   mech
2    3   vijay    pune  civil
3    4  ramesh     mum    NaN
4    5    ravi  satara    NaN
5    6     NaN     NaN  elect
6    7     NaN     NaN     ai

In [54]:
joins.isnull().sum()

eid      0
ename    2
city     2
dept     2
dtype: int64

In [55]:
joins[joins.isnull().any(axis=1)]

   eid   ename    city   dept
3    4  ramesh     mum    NaN
4    5    ravi  satara    NaN
5    6     NaN     NaN  elect
6    7     NaN     NaN     ai

In [56]:
joins[joins.isna().any(axis=1)]

   eid   ename    city   dept
3    4  ramesh     mum    NaN
4    5    ravi  satara    NaN
5    6     NaN     NaN  elect
6    7     NaN     NaN     ai

In [60]:
df.merge(df1, how='outer', indicator=True)

   eid   ename    city   dept      _merge
0    1    amit     kop     it        both
1    2   kumar   kagal   mech        both
2    3   vijay    pune  civil        both
3    4  ramesh     mum    NaN   left_only
4    5    ravi  satara    NaN   left_only
5    6     NaN     NaN  elect  right_only
6    7     NaN     NaN     ai  right_only

In [61]:
df.merge(df1, how='left', indicator=True)

   eid   ename    city   dept     _merge
0    1    amit     kop     it       both
1    2   kumar   kagal   mech       both
2    3   vijay    pune  civil       both
3    4  ramesh     mum    NaN  left_only
4    5    ravi  satara    NaN  left_only

In [63]:
df.merge(df1, how='left', indicator=True).query('_merge == "left_only"').drop('_merge', axis=1)

   eid   ename    city dept
3    4  ramesh     mum  NaN
4    5    ravi  satara  NaN